import Sidebar from "@/app/(examples)/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ExampleRootLayout({ children }) {
  return (
    <div className="grid h-screen grid-cols-4">
      <Sidebar />
      <main className="col-span-3">{children}</main>
    </div>
  );
}
