import { AppBar } from "@/components/AppBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
  return (
    <div className="grid h-screen grid-cols-1 md:grid-cols-[240px_1fr]">
      <div className="hidden md:block">
        <AppBar />
      </div>
      <main className="w-full overflow-y-auto md:border-l">{children}</main>
    </div>
  );
}
