export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
  return <main className="col-span-3">{children}</main>;
}
