const words = [
  "lorem",
  "ipsum",
  "dolor",
  "sit",
  "amet",
  "consectetur",
  "adipiscing",
  "elit",
  "praesent",
  "tellus",
  "magna",
  "rutrum",
  "quis",
  "posuere",
  "at",
  "non",
  "nulla",
  "pellentesque",
  "blandit",
  "mauris",
  "viverra",
  "tincidunt",
  "nisi",
  "ante",
  "elementum",
  "nec",
  "ultricies",
  "erat",
  "orci",
  "nullam",
  "ex",
  "enim",
  "mattis",
  "iaculis",
  "vulputate",
  "id",
  "morbi",
  "bibendum",
  "ut",
  "ornare",
  "aliquam",
  "tristique",
  "eget",
  "massa",
  "in",
  "tortor",
  "hendrerit",
  "egestas",
  "purus",
  "ac",
  "est",
  "mauris",
  "imperdiet",
  "sagittis",
  "metus",
  "molestie",
  "venenatis",
  "nibh",
  "scelerisque",
  "sed",
  "ligula",
  "arcu",
  "vehicula",
  "tempus",
  "integer",
  "cursus",
  "dui",
  "finibus",
  "interdum",
  "lectus",
  "felis",
  "vitae",
  "efficitur",
  "sem",
  "a",
  "aenean",
  "odio",
  "faucibus",
  "laoreet",
  "proin",
  "vel",
  "in",
  "eleifend",
  "pulvinar",
  "et",
  "vivamus",
  "eu",
  "nisl",
  "neque",
  "ullamcorper",
  "diam",
  "nulla",
  "mollis",
  "feugiat",
  "phasellus",
  "lobortis",
  "urna",
  "vestibulum",
  "lorem",
  "libero",
  "pellentesque",
  "exsuspendisse",
  "turpis",
  "rhoncus",
  "fermentum",
  "vestibulum",
  "quam",
  "porta",
  "maecenas",
  "curabitur",
  "maximus",
  "volutpat",
  "condimentum",
  "sed",
  "pretium",
  "sapien",
  "varius",
  "donec",
  "eros",
  "etiam",
  "porttitor",
  "dapibus",
  "lorem",
  "mollisfusce",
  "aliquet",
  "augue",
  "fusce",
  "pharetra",
  "nunc",
  "aliquam",
  "convallis",
  "placerat",
  "accumsan",
  "mi",
  "semper",
  "sollicitudinetiam",
  "malesuada",
  "commodo",
  "sollicitudin",
  "duis",
  "facilisis",
  "suspendisse",
  "tempor",
  "elitdonec",
  "consequat",
  "ut",
  "auctor",
  "fringilla",
  "euismod",
  "dictum",
  "leo",
  "erospraesent",
  "risus",
  "lacus",
  "cras",
  "interdumsed",
  "lacinia",
  "dignissim",
  "sodales",
  "mattisdonec",
  "gravida",
  "justo",
  "ultrices",
  "velit",
  "orciinteger",
  "potenti",
  "luctus",
  "egestasduis",
  "congue",
  "quisque",
  "suscipit",
  "nunc",
  "nam",
  "dolorcras",
  "interdum",
  "fames",
  "primis",
  "tinciduntnam",
  "interdummaecenas",
  "sapienquisque",
  "volutpatvestibulum",
  "pretiumduis",
  "dolorcurabitur",
  "orci",
  "natoque",
  "penatibus",
  "magnis",
  "dis",
  "parturient",
  "montes",
  "nascetur",
  "ridiculus",
  "mus",
  "facilisi",
  "ullamcorperdonec",
  "diamin",
  "egetquisque",
  "ipsumin",
  "hac",
  "habitasse",
  "platea",
  "dictumst",
  "leoaenean",
  "habitant",
  "morbi",
  "senectus",
  "netus",
  "ligulanunc",
  "class",
  "aptent",
  "taciti",
  "sociosqu",
  "ad",
  "litora",
  "torquent",
  "per",
  "conubia",
  "nostra",
  "inceptos",
  "himenaeos",
  "placeratphasellus",
  "massaproin",
  "semsed",
  "diampellentesque",
  "duidonec",
  "congueproin",
  "semproin",
  "inut",
  "dignissimnullam",
  "enimpellentesque",
  "egestasnunc",
  "feugiatmaecenas",
  "suscipitsed",
  "risusaliquam",
  "consequatpraesent",
  "semperaenean",
  "eratdonec",
  "viverracurabitur",
  "acmorbi",
  "dolorphasellus",
  "sempellentesque",
  "cursusmaecenas",
  "quamdonec",
  "himenaeossed",
  "tellusdonec",
  "estetiam",
  "sollicitudinduis",
  "maurisnulla",
  "velitinteger",
  "tellusmauris",
  "tortornulla",
  "auctorfusce",
  "tempussed",
  "ultriciesin",
  "ullamcorperproin",
  "ipsumcras",
  "ipsumpraesent",
  "portaut",
  "necnulla",
  "dignissimnunc",
  "tinciduntdonec",
  "mauriscurabitur",
  "eleifendaliquam",
  "loremsed",
  "cubilia",
  "curae",
  "maecenas",
  "idsed",
  "faucibuspellentesque",
  "muspraesent",
  "pretiumetiam",
  "utvestibulum",
  "arcucurabitur",
  "tortormauris",
  "leoetiam",
  "estcras",
  "curae",
  "tortorpraesent",
  "eratnulla",
  "turpisetiam",
  "scelerisquesed",
  "hendrerit",
  "suspendisse",
  "ligulas",
  "malesuadanullam",
  "posuerepellentesque",
  "elementumvestibulum",
  "liberosed",
  "tinciduntaliquam",
  "maximusproin",
  "felisphasellus",
  "commodophasellus",
  "turpisproin",
  "eratduis",
  "sapienmauris",
  "rutrumvestibulum",
  "tortorsuspendisse",
  "magnased",
  "euvestibulum",
  "liberoquisque",
  "auctornulla",
  "eratin",
  "accumsanpellentesque",
  "musquisque",
  "eratphasellus",
  "volutpatinteger",
  "miproin",
  "tinciduntsed",
  "potentimauris",
  "insed",
  "seddonec",
  "urnain",
  "sapien",
];

const LoremIpsum = ({ p = 1 }) => {
  const paragraphs = p;
  const minSentences = 3;
  const maxSentences = 7;
  const minWords = 3;
  const maxWords = 15;

  function renderSentence(numOfWords) {
    let sentence = "";

    for (let i = 0; i < numOfWords; i++) {
      sentence += words[Math.floor(Math.random() * words.length)] + " ";
    }

    return (sentence[0].toUpperCase() + sentence.slice(1)).trim() + ".";
  }

  function renderParagraphs() {
    let sentences = [];

    for (let i = 0; i < paragraphs; i++) {
      sentences.push([]);
      const numOfSentences = Math.floor(
        Math.random() *
          (Math.floor(maxSentences) - Math.ceil(minSentences) + 1) +
          Math.ceil(minSentences),
      );

      for (let j = 0; j < numOfSentences; j++) {
        const numOfWords = Math.floor(
          Math.random() * (Math.floor(maxWords) - Math.ceil(minWords) + 1) +
            Math.ceil(minWords),
        );
        sentences[i].push(renderSentence(numOfWords));
      }
    }

    return sentences;
  }

  const paragraphsArr = renderParagraphs();

  return (
    <>
      {paragraphsArr.map((item, i) => {
        return (
          <p key={i}>
            {item.map((sentence) => {
              return sentence + " ";
            })}
          </p>
        );
      })}
    </>
  );
};

export default LoremIpsum;
